// languages.ts
const languages = {
    fr: {
        footer_button_contact: "Contactez-moi",
        homepage_title_job_name: "Développeur web",
        homepage_title_projects: "Projets",
        homepage_title_about_me: "À propos de moi",
        homepage_title_education: "Formation",
        homepage_about_me_age: "21 ans",
        homepage_about_me_from: "De France",
        homepage_about_me_activity: "Étudiant en ingénieure logicielle",
        footer_language_select: "EN",
        navbar_language_select: "EN",
        navbar_title_projects: "Projets",
        navbar_title_about_me: "À propos de moi",
        navbar_title_contact: "Contact",
        project_taskmanager_title: "Gestionnaire de services",
        project_taskmanager_description:  "Site web développé pour simplifier l'organisation des tâches ménagères dans une école. Permet à un responsable de répartir les tâches par jour, imprimer l'emploi du temps, et faciliter la communication avec les élèves. Projet demandé par un établissement scolaire.",
        project_letsgetrich_title: "LetsGetRich",
        project_letsgetrich_description:  "Site web développé pour simplifier l'organisation des tâches ménagères dans une école. Permet à un responsable de répartir les tâches par jour, imprimer l'emploi du temps, et faciliter la communication avec les élèves. Projet demandé par un établissement scolaire.",
        contact_form_title: 'Envoyez-moi un message',
        contact_form_firstname_label: 'Votre prenom',
        contact_form_lastname_label: 'Votre nom',
        contact_form_email_label: 'Votre adresse email',
        contact_form_message_label: 'Votre message',
        contact_form_submit_label: 'Envoyer le message',
        contact_form_message_placeholder: 'Bonjour...',
        contact_form_message_success: 'Votre message a été envoyé avec succès !',
        contact_form_message_failed: 'Il y a eu une erreur lors de l\'envoi de votre message, vous pouvez l\'envoyer directement à mon adresse email.',
        contact_information_title: 'ou prenez mes informations de contact !',
        contact_information_email_title: 'Email :',
        contact_information_phone_title: 'Numéro de téléphone :',
        contact_information_address_title: 'Adresse :',
        contact_information_linkedin_title: 'LinkedIn :',
        about_me_who_text: 'Bienvenue sur mon portfolio ! Je suis Esteban GOMEZ, un développeur français de 21 ans. La musique guide mes lignes de code, tandis que ma passion pour la mode et le design se traduit par des interfaces utilisateur sobres et esthétiques. Explorez mon portfolio, une fusion de passion et de technologie, constamment en évolution.',
        about_me_studies_title: 'Mon parcours',
        about_me_studies_bac_title: 'Bac scientifique',
        about_me_studies_bac_where: 'Lycée Édouard Branly',
        about_me_studies_iut_title: 'DUT informatique',
        about_me_studies_iut_where: 'IUT de Nantes',
        about_me_studies_imt_title: 'Formation d\'Ingénieur spécialité ingénierie logicielle (FIL)',
        about_me_studies_imt_where: 'IMT Atlantique',
        about_me_job_title: 'Mes expériences',
        about_me_job_pladis_title: 'Apprentis techniciens informatiques',
        about_me_job_kosmos_title: 'Apprentis ingénieur logiciel',
    },
    en: {
        footer_button_contact: "Get in Touch",
        homepage_title_job_name: "Web developer",
        homepage_title_projects: "Projects",
        homepage_title_about_me: "About me",
        homepage_title_education: "Education",
        homepage_about_me_age: "21 years old",
        homepage_about_me_from: "From France",
        homepage_about_me_activity: "Software engineering student",
        footer_language_select: "FR",
        navbar_language_select: "FR",
        navbar_title_projects: "Projects",
        navbar_title_about_me: "About me",
        navbar_title_contact: "Contact",
        project_taskmanager_title: "Task manager",
        project_taskmanager_description:  "Website developed to simplify the organisation of household chores in a school. It enables the person in charge to allocate tasks by day, print out the timetable and facilitate communication with pupils. Project requested by a school.",
        project_letsgetrich_title: "LetsGetRich",
        project_letsgetrich_description:  "Site web développé pour simplifier l'organisation des tâches ménagères dans une école. Permet à un responsable de répartir les tâches par jour, imprimer l'emploi du temps, et faciliter la communication avec les élèves. Projet demandé par un établissement scolaire.",
        contact_form_title: 'Send me a message',
        contact_form_firstname_label: 'Your firstname',
        contact_form_lastname_label: 'Your lastname',
        contact_form_email_label: 'Your email address',
        contact_form_message_label: 'Your message',
        contact_form_submit_label: 'Send message',
        contact_form_message_placeholder: 'Hello...',
        contact_form_message_success: 'Your message has been sent successfully!',
        contact_form_message_failed: 'There was an error sending your message, you can send it directly to my email address.',
        contact_information_title: 'or take my contact details!',
        contact_information_email_title: 'Email:',
        contact_information_phone_title: 'Phone number:',
        contact_information_address_title: 'Address:',
        contact_information_linkedin_title: 'LinkedIn:',
        about_me_who_text: 'Welcome to my portfolio! I\'m Esteban GOMEZ, a 21-year-old French developer. Music guides my lines of code, while my passion for fashion and design translates into sleek and aesthetic user interfaces. Explore my portfolio, a fusion of passion and technology, constantly evolving.',
        about_me_studies_title: 'My education',
        about_me_studies_bac_title: 'Scientific baccalauréat',
        about_me_studies_bac_where: 'Édouard Branly High School',
        about_me_studies_iut_title: 'Equivalent to an HND in IT',
        about_me_studies_iut_where: 'Nantes IUT',
        about_me_studies_imt_title: 'Engineering degree specialising in software engineering (FIL)',
        about_me_studies_imt_where: 'IMT Atlantique',
        about_me_job_title: 'My experiences',
        about_me_job_pladis_title: 'Apprentices IT Technician',
        about_me_job_kosmos_title: 'Apprentice software engineers',
    },
};

export default languages;
